/*
 * UberAPI.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/13/2016
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using UberAPI.PCL;

namespace UberAPI.PCL.Models
{
    public class Driver : INotifyPropertyChanged 
    {
        // These fields hold the values for the public properties.
        private string name;
        private string phoneNumber;
        private string pictureUrl;
        private double rating;

        /// <summary>
        /// The first name of the driver.
        /// </summary>
        [JsonProperty("name")]
        public string Name 
        { 
            get 
            {
                return this.name; 
            } 
            set 
            {
                this.name = value;
                onPropertyChanged("Name");
            }
        }

        /// <summary>
        /// The formatted phone number for contacting the driver.
        /// </summary>
        [JsonProperty("phone_number")]
        public string PhoneNumber 
        { 
            get 
            {
                return this.phoneNumber; 
            } 
            set 
            {
                this.phoneNumber = value;
                onPropertyChanged("PhoneNumber");
            }
        }

        /// <summary>
        /// The URL to the photo of the driver.
        /// </summary>
        [JsonProperty("picture_url")]
        public string PictureUrl 
        { 
            get 
            {
                return this.pictureUrl; 
            } 
            set 
            {
                this.pictureUrl = value;
                onPropertyChanged("PictureUrl");
            }
        }

        /// <summary>
        /// The driver's star rating out of 5 stars.
        /// </summary>
        [JsonProperty("rating")]
        public double Rating 
        { 
            get 
            {
                return this.rating; 
            } 
            set 
            {
                this.rating = value;
                onPropertyChanged("Rating");
            }
        }

        /// <summary>
        /// Property changed event for observer pattern
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Raises event when a property is changed
        /// </summary>
        /// <param name="propertyName">Name of the changed property</param>
        protected void onPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
} 