/*
 * UberAPI.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/13/2016
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using UberAPI.PCL;

namespace UberAPI.PCL.Models
{
    public class GetPriceEstimatesInput : INotifyPropertyChanged 
    {
        // These fields hold the values for the public properties.
        private double endLatitude;
        private double endLongitude;
        private double startLatitude;
        private double startLongitude;

        /// <summary>
        /// Latitude component of end location.
        /// </summary>
        [JsonProperty("end_latitude")]
        public double EndLatitude 
        { 
            get 
            {
                return this.endLatitude; 
            } 
            set 
            {
                this.endLatitude = value;
                onPropertyChanged("EndLatitude");
            }
        }

        /// <summary>
        /// Longitude component of end location.
        /// </summary>
        [JsonProperty("end_longitude")]
        public double EndLongitude 
        { 
            get 
            {
                return this.endLongitude; 
            } 
            set 
            {
                this.endLongitude = value;
                onPropertyChanged("EndLongitude");
            }
        }

        /// <summary>
        /// Latitude component of start location.
        /// </summary>
        [JsonProperty("start_latitude")]
        public double StartLatitude 
        { 
            get 
            {
                return this.startLatitude; 
            } 
            set 
            {
                this.startLatitude = value;
                onPropertyChanged("StartLatitude");
            }
        }

        /// <summary>
        /// Longitude component of start location.
        /// </summary>
        [JsonProperty("start_longitude")]
        public double StartLongitude 
        { 
            get 
            {
                return this.startLongitude; 
            } 
            set 
            {
                this.startLongitude = value;
                onPropertyChanged("StartLongitude");
            }
        }

        /// <summary>
        /// Property changed event for observer pattern
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Raises event when a property is changed
        /// </summary>
        /// <param name="propertyName">Name of the changed property</param>
        protected void onPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
} 