/*
 * UberAPI.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/13/2016
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using UberAPI.PCL;

namespace UberAPI.PCL.Models
{
    public class History : INotifyPropertyChanged 
    {
        // These fields hold the values for the public properties.
        private double distance;
        private Location endLocation;
        private int endTime;
        private string productId;
        private int requestTime;
        private Location startLocation;
        private int startTime;
        private string status;
        private string uuid;

        /// <summary>
        /// Distance travelled
        /// </summary>
        [JsonProperty("distance")]
        public double Distance 
        { 
            get 
            {
                return this.distance; 
            } 
            set 
            {
                this.distance = value;
                onPropertyChanged("Distance");
            }
        }

        /// <summary>
        /// Location where journey ended
        /// </summary>
        [JsonProperty("end_location")]
        public Location EndLocation 
        { 
            get 
            {
                return this.endLocation; 
            } 
            set 
            {
                this.endLocation = value;
                onPropertyChanged("EndLocation");
            }
        }

        /// <summary>
        /// Time of journey end
        /// </summary>
        [JsonProperty("end_time")]
        public int EndTime 
        { 
            get 
            {
                return this.endTime; 
            } 
            set 
            {
                this.endTime = value;
                onPropertyChanged("EndTime");
            }
        }

        /// <summary>
        /// The product that was used
        /// </summary>
        [JsonProperty("product_id")]
        public string ProductId 
        { 
            get 
            {
                return this.productId; 
            } 
            set 
            {
                this.productId = value;
                onPropertyChanged("ProductId");
            }
        }

        /// <summary>
        /// Time when requested
        /// </summary>
        [JsonProperty("request_time")]
        public int RequestTime 
        { 
            get 
            {
                return this.requestTime; 
            } 
            set 
            {
                this.requestTime = value;
                onPropertyChanged("RequestTime");
            }
        }

        /// <summary>
        /// Location of starting the journey
        /// </summary>
        [JsonProperty("start_location")]
        public Location StartLocation 
        { 
            get 
            {
                return this.startLocation; 
            } 
            set 
            {
                this.startLocation = value;
                onPropertyChanged("StartLocation");
            }
        }

        /// <summary>
        /// Time of starting the journey
        /// </summary>
        [JsonProperty("start_time")]
        public int StartTime 
        { 
            get 
            {
                return this.startTime; 
            } 
            set 
            {
                this.startTime = value;
                onPropertyChanged("StartTime");
            }
        }

        /// <summary>
        /// Status of the product e.g., completed
        /// </summary>
        [JsonProperty("status")]
        public string Status 
        { 
            get 
            {
                return this.status; 
            } 
            set 
            {
                this.status = value;
                onPropertyChanged("Status");
            }
        }

        /// <summary>
        /// History item id
        /// </summary>
        [JsonProperty("uuid")]
        public string Uuid 
        { 
            get 
            {
                return this.uuid; 
            } 
            set 
            {
                this.uuid = value;
                onPropertyChanged("Uuid");
            }
        }

        /// <summary>
        /// Property changed event for observer pattern
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Raises event when a property is changed
        /// </summary>
        /// <param name="propertyName">Name of the changed property</param>
        protected void onPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
} 