/*
 * UberAPI.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/13/2016
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using UberAPI.PCL;

namespace UberAPI.PCL.Models
{
    public class PromotionsResponse : INotifyPropertyChanged 
    {
        // These fields hold the values for the public properties.
        private string displayText;
        private string localizedValue;
        private string type;

        /// <summary>
        /// A localized string we recommend to use when offering the promotion to users.
        /// </summary>
        [JsonProperty("display_text")]
        public string DisplayText 
        { 
            get 
            {
                return this.displayText; 
            } 
            set 
            {
                this.displayText = value;
                onPropertyChanged("DisplayText");
            }
        }

        /// <summary>
        /// The value of the promotion that is available to a user in this location in the local currency.
        /// </summary>
        [JsonProperty("localized_value")]
        public string LocalizedValue 
        { 
            get 
            {
                return this.localizedValue; 
            } 
            set 
            {
                this.localizedValue = value;
                onPropertyChanged("LocalizedValue");
            }
        }

        /// <summary>
        /// The type of the promo which is either "trip_credit" or "account_credit".
        /// </summary>
        [JsonProperty("type")]
        public string Type 
        { 
            get 
            {
                return this.type; 
            } 
            set 
            {
                this.type = value;
                onPropertyChanged("Type");
            }
        }

        /// <summary>
        /// Property changed event for observer pattern
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Raises event when a property is changed
        /// </summary>
        /// <param name="propertyName">Name of the changed property</param>
        protected void onPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
} 