/*
 * UberAPI.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/13/2016
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using UberAPI.PCL;

namespace UberAPI.PCL.Models
{
    public class RequestBody : INotifyPropertyChanged 
    {
        // These fields hold the values for the public properties.
        private double endLatitude;
        private double endLongitude;
        private string productId;
        private double startLatitude;
        private double startLongitude;
        private string surgeConfirmationId;

        /// <summary>
        /// The final or destination latitude.
        /// </summary>
        [JsonProperty("end_latitude")]
        public double EndLatitude 
        { 
            get 
            {
                return this.endLatitude; 
            } 
            set 
            {
                this.endLatitude = value;
                onPropertyChanged("EndLatitude");
            }
        }

        /// <summary>
        /// The final or destination longitude.
        /// </summary>
        [JsonProperty("end_longitude")]
        public double EndLongitude 
        { 
            get 
            {
                return this.endLongitude; 
            } 
            set 
            {
                this.endLongitude = value;
                onPropertyChanged("EndLongitude");
            }
        }

        /// <summary>
        /// The unique ID of the product being requested.
        /// </summary>
        [JsonProperty("product_id")]
        public string ProductId 
        { 
            get 
            {
                return this.productId; 
            } 
            set 
            {
                this.productId = value;
                onPropertyChanged("ProductId");
            }
        }

        /// <summary>
        /// The beginning or "pickup" latitude.
        /// </summary>
        [JsonProperty("start_latitude")]
        public double StartLatitude 
        { 
            get 
            {
                return this.startLatitude; 
            } 
            set 
            {
                this.startLatitude = value;
                onPropertyChanged("StartLatitude");
            }
        }

        /// <summary>
        /// The beginning or "pickup" longitude.
        /// </summary>
        [JsonProperty("start_longitude")]
        public double StartLongitude 
        { 
            get 
            {
                return this.startLongitude; 
            } 
            set 
            {
                this.startLongitude = value;
                onPropertyChanged("StartLongitude");
            }
        }

        /// <summary>
        /// The unique identifier of the surge session for a user. Required when returned from a 409 Conflict response on previous POST attempt.
        /// </summary>
        [JsonProperty("surge_confirmation_id")]
        public string SurgeConfirmationId 
        { 
            get 
            {
                return this.surgeConfirmationId; 
            } 
            set 
            {
                this.surgeConfirmationId = value;
                onPropertyChanged("SurgeConfirmationId");
            }
        }

        /// <summary>
        /// Property changed event for observer pattern
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Raises event when a property is changed
        /// </summary>
        /// <param name="propertyName">Name of the changed property</param>
        protected void onPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
} 