/*
 * UberAPI.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/13/2016
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using UberAPI.PCL;

namespace UberAPI.PCL.Models
{
    public class UserProfile : INotifyPropertyChanged 
    {
        // These fields hold the values for the public properties.
        private string email;
        private string firstName;
        private string lastName;
        private string picture;
        private string promoCode;

        /// <summary>
        /// Email address of the Uber user
        /// </summary>
        [JsonProperty("email")]
        public string Email 
        { 
            get 
            {
                return this.email; 
            } 
            set 
            {
                this.email = value;
                onPropertyChanged("Email");
            }
        }

        /// <summary>
        /// First name of the Uber user.
        /// </summary>
        [JsonProperty("first_name")]
        public string FirstName 
        { 
            get 
            {
                return this.firstName; 
            } 
            set 
            {
                this.firstName = value;
                onPropertyChanged("FirstName");
            }
        }

        /// <summary>
        /// Last name of the Uber user.
        /// </summary>
        [JsonProperty("last_name")]
        public string LastName 
        { 
            get 
            {
                return this.lastName; 
            } 
            set 
            {
                this.lastName = value;
                onPropertyChanged("LastName");
            }
        }

        /// <summary>
        /// Image URL of the Uber user.
        /// </summary>
        [JsonProperty("picture")]
        public string Picture 
        { 
            get 
            {
                return this.picture; 
            } 
            set 
            {
                this.picture = value;
                onPropertyChanged("Picture");
            }
        }

        /// <summary>
        /// Promo code of the Uber user.
        /// </summary>
        [JsonProperty("promo_code")]
        public string PromoCode 
        { 
            get 
            {
                return this.promoCode; 
            } 
            set 
            {
                this.promoCode = value;
                onPropertyChanged("PromoCode");
            }
        }

        /// <summary>
        /// Property changed event for observer pattern
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Raises event when a property is changed
        /// </summary>
        /// <param name="propertyName">Name of the changed property</param>
        protected void onPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
} 