/*
 * UberAPI.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/13/2016
 */
using System;

namespace UberAPI.PCL
{
    public partial class Configuration
    {
        //The base Uri for API calls
        public static string BaseUri = "https://api.uber.com/v1";

        //The OAuth 2.0 access token to be set before API calls
        //TODO: Replace the OAuthAccessToken with an appropriate value
        public static string OAuthAccessToken = "TODO: Replace";

    }
}